add_compile_definitions(
    BOARD_NAME="Pimoroni TINY2350"
    PIO_USB_DP_PIN_DEFAULT=2
    LED_RGB_PWM=1
    LED_RGB_ACTIVE_LOW=1
    LED_RGB_RED_PIN=TINY2350_LED_R_PIN
    LED_RGB_GREEN_PIN=TINY2350_LED_G_PIN
    LED_RGB_BLUE_PIN=TINY2350_LED_B_PIN
)
